name: Auto Update Valuation

permissions:
  contents: write

on:
  schedule:
    - cron: '0 22 * * *' # 北京时间 06:00
    - cron: '0 10 * * *' # 北京时间 18:00
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance matplotlib akshare beautifulsoup4 lxml

      - name: Run Script
        run: python update_valuation.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
